# Generated by Django 5.0.4 on 2024-04-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='goup_name',
            new_name='group_name',
        ),
    ]
